// Per-run collection getters, scientist-authored input, reports, and share
// grants. Extracted from `./runs`, which re-exports the public functions so
// callers keep importing them from '@/api/runs'.

import type {
  ClaimEvidenceRow,
  Evidence,
  Hypothesis,
  MatchRow,
  ProximityEdge,
  ReportShare,
  Review,
  SafetyDecision,
  SharedGoalReport,
} from './run_types';
import type {CodeVariant} from './discovery_types';
import type {Report} from './report_types';
import {
  API_BASE_URL,
  assertOk,
  clientHeaders,
  fetchField,
  fetchJson,
  jsonRequest,
  parseJson,
} from './runs_http';

/**
 * Fetches a run sub-resource `/api/runs/{id}/{key}` that the API returns
 * wrapped as `{[key]: T[]}`.
 *
 * @param id Run identifier.
 * @param key Sub-resource path segment, doubling as the response key.
 * @returns The unwrapped array.
 */
function getRunList<T>(id: string, key: string): Promise<T[]> {
  return fetchField<string, T[]>(`/api/runs/${id}/${key}`, key, {
    headers: clientHeaders(),
  });
}

/**
 * Fetches the hypotheses generated by a run.
 *
 * @param id Run identifier.
 * @returns The run's hypotheses.
 */
export function getHypotheses(id: string): Promise<Hypothesis[]> {
  return getRunList<Hypothesis>(id, 'hypotheses');
}

/**
 * Fetches a discovery run's code variants, in attempt order.
 *
 * @param id Run identifier.
 * @returns Every attempt the run made, failures included.
 */
export function getCodeVariants(id: string): Promise<CodeVariant[]> {
  return getRunList<CodeVariant>(id, 'variants');
}

/**
 * Fetches one variant with its metrics, artifacts, and full source.
 *
 * @param id Run identifier.
 * @param variantId Variant identifier.
 * @returns The variant's detail record.
 */
export function getCodeVariant(
  id: string,
  variantId: string,
): Promise<CodeVariant> {
  return fetchJson<CodeVariant>(`/api/runs/${id}/variants/${variantId}`, {
    headers: clientHeaders(),
  });
}

/**
 * Fetches the literature evidence gathered for a run.
 *
 * @param id Run identifier.
 * @returns The run's evidence records.
 */
export function getEvidence(id: string): Promise<Evidence[]> {
  return getRunList<Evidence>(id, 'evidence');
}

/**
 * Fetches the pairwise tournament matches for a run.
 *
 * @param id Run identifier.
 * @returns The run's match rows.
 */
export function getMatches(id: string): Promise<MatchRow[]> {
  return getRunList<MatchRow>(id, 'matches');
}

/**
 * Fetches the reviewer critiques for a run's hypotheses.
 *
 * @param id Run identifier.
 * @returns The run's reviews.
 */
export function getReviews(id: string): Promise<Review[]> {
  return getRunList<Review>(id, 'reviews');
}

/** Fetch the versioned safety audit trail for a run. */
export function getSafety(id: string): Promise<SafetyDecision[]> {
  return getRunList<SafetyDecision>(id, 'safety');
}

/** Resolve one held safety decision as the identified run owner. */
export function adjudicateSafety(
  runId: string,
  decisionId: number,
  resolution: 'approved' | 'rejected',
): Promise<{decision_id: number; resolution: string}> {
  return fetchJson(
    `/api/runs/${runId}/safety/${decisionId}/adjudicate`,
    jsonRequest({resolution}, true),
  );
}

/**
 * Fetches the claim-level entailment graph for a run's hypotheses.
 *
 * The endpoint path (`claim-evidence`) differs from the response key
 * (`claim_evidence`), so this cannot use the `getRunList` shorthand.
 *
 * @param id Run identifier.
 * @returns The run's claim-evidence edges.
 */
export function getClaimEvidence(id: string): Promise<ClaimEvidenceRow[]> {
  return fetchField<'claim_evidence', ClaimEvidenceRow[]>(
    `/api/runs/${id}/claim-evidence`,
    'claim_evidence',
    {headers: clientHeaders()},
  );
}

/** Return the persisted weighted hypothesis proximity graph. */
export function getProximity(id: string): Promise<ProximityEdge[]> {
  return getRunList<ProximityEdge>(id, 'proximity');
}

/** Submit a scientist-authored hypothesis through the shared safety gate. */
export function addScientistHypothesis(
  runId: string,
  input: {title?: string; statement: string; author: string},
): Promise<{admitted: boolean; id?: string; safety: {outcome: string}}> {
  return fetchJson(`/api/runs/${runId}/hypotheses`, jsonRequest(input, true));
}

/** Attach a scientist verdict to an existing hypothesis. */
export function addScientistReview(
  runId: string,
  input: {
    hypothesis_id: string;
    author: string;
    verdict: 'support' | 'oppose' | 'revise';
    critique: string;
  },
): Promise<{recorded: boolean}> {
  return fetchJson(`/api/runs/${runId}/reviews`, jsonRequest(input, true));
}

/** Upload and index a private scientific document for subsequent tasks. */
export function uploadRunDocument(
  runId: string,
  file: File,
): Promise<{
  id: string;
  indexed: boolean;
  sha256: string;
  byte_size: number;
  mime_type: string;
  extraction_tool: string;
}> {
  const body = new FormData();
  body.set('file', file);
  body.set('consent', 'true');
  return fetchJson(`/api/runs/${runId}/attachments/upload`, {
    method: 'POST',
    headers: clientHeaders(),
    body,
  });
}

/**
 * Fetches a run's final report, or null if none exists yet.
 *
 * @param id Run identifier.
 * @returns The report, or null when not yet generated.
 */
export async function getReport(id: string): Promise<Report | null> {
  const res = await fetch(`${API_BASE_URL}/api/runs/${id}/report`, {
    headers: clientHeaders(),
  });
  if (res.status === 404) return null; // no report yet, not an error
  return parseJson<Report>(res);
}

/**
 * Fetches the Markdown Goal Report through the authenticated API.
 *
 * The download surface uses this rather than a direct URL: the endpoint
 * accepts the standard auth headers, so no credential ever rides in a query
 * string (where it would leak into history, screenshots, and proxy logs).
 *
 * @param id Run identifier.
 * @returns The report Markdown, or null when no report exists yet (404).
 */
export async function fetchReportMarkdown(id: string): Promise<string | null> {
  const res = await fetch(`${API_BASE_URL}/api/runs/${id}/report.md`, {
    headers: clientHeaders(),
  });
  if (res.status === 404) return null; // no report yet, not an error
  await assertOk(res);
  return res.text();
}

/** Enables public read-only access and returns the one-time bearer token. */
export function createReportShare(id: string): Promise<ReportShare> {
  return fetchJson(`/api/runs/${id}/shares`, jsonRequest({}, true));
}

/** Lists active grants without disclosing their bearer tokens. */
export function listReportShares(id: string): Promise<ReportShare[]> {
  return getRunList<ReportShare>(id, 'shares');
}

/** Revokes one public report capability. */
export async function revokeReportShare(
  runId: string,
  shareId: string,
): Promise<void> {
  const response = await fetch(
    `${API_BASE_URL}/api/runs/${runId}/shares/${shareId}`,
    {method: 'DELETE', headers: clientHeaders()},
  );
  await assertOk(response);
}

/** Loads a public read-only Goal Report without a client ownership header. */
export function getSharedGoalReport(token: string): Promise<SharedGoalReport> {
  return fetchJson(`/api/shared/${token}`);
}
