"""Report header rendering: title, the run's configuration, and provenance.

Split out of ``report_markdown`` to keep that module within the size cap.
Renders, in the published order (MASH report L3-40 then L41): the title and
provider line, "Research Goal Details" -- goal, requirements, attributes,
criteria, all collected by ``run_modes.setup_config`` into the run's
persisted ``setup`` block but never rendered before (R12-8) -- then a
provenance and caution line naming this system and when the report was
prepared (R12-20), then the optional summary paragraph. The title/provider
line renders through its own function, separate from the rest: R14-1's
table of contents is inserted right after it and before everything else,
so the always-present opening has to be callable on its own.
"""

from __future__ import annotations

import datetime
from typing import Any

from app.run_modes import attribute_display_strings, criteria_display_strings

# Kept close to Google's published wording ("Prepared by AI co-scientist on
# 2026-06-12. For research purposes only.") but naming this system, not
# Google's -- claiming to be Google's product would misattribute the report.
_SYSTEM_NAME = "Co-Scientist"

# R14-4: byte-identical to the per-hypothesis disclaimer (R14-13,
# ``report_markdown_hypothesis._HYPOTHESIS_DISCLAIMER``, re-exported from
# here so the two never drift). Google's published research-overview.md
# carries this same "experimental system ... may be wrong" wording at the
# report level (line 5), distinct from the short provenance/caution line
# above -- one names this system and when the report ran, the other states
# what the system is and cautions that its output may be wrong. Defined
# here, the lower module in the import chain (``report_markdown_hypothesis``
# already imports ``_SYSTEM_NAME`` from this module), so the per-hypothesis
# copy can import this constant instead of duplicating the string.
_ABOUT_DISCLOSURE = (
    "**About**: *This is an experimental system for generating novel and"
    " testable hypotheses. The hypotheses are generated by a model and"
    " may be wrong. For research purposes only.*"
)


def _render_setup_list(label: str, values: list[str]) -> list[str]:
    """Render a 'Label:' bullet list, or nothing when there is no content."""
    if not values:
        return []
    return [f"**{label}:**\n"] + [f"- {value}" for value in values] + [""]


def _plain_setup_strings(items: Any) -> list[str]:
    """Coerce a Requirements/Attributes setup value into display strings."""
    return [str(item) for item in items or [] if str(item).strip()]


def _render_research_goal_details(
    research_goal: str, setup: dict[str, Any] | None
) -> list[str]:
    """Render 'Research Goal Details': goal, requirements, attributes, criteria.

    Nothing renders when the run carries no setup block (a report persisted
    before this field existed) or an empty one. Attributes may be the
    legacy free-prose list or the R12-5 structured axis list, and criteria
    may be the legacy free-prose list or the R12-4 ``{"name", "value"}``
    pair list -- ``attribute_display_strings``/``criteria_display_strings``
    render every shape the same way, so an older persisted run keeps
    reading exactly as it always did.
    """
    if not isinstance(setup, dict):
        return []
    fields = [
        _render_setup_list(
            "Requirements", _plain_setup_strings(setup.get("requirements"))
        ),
        _render_setup_list(
            "Attributes", attribute_display_strings(setup.get("attributes"))
        ),
        _render_setup_list(
            "Criteria", criteria_display_strings(setup.get("criteria"))
        ),
    ]
    if not any(fields):
        return []
    lines = ["## Research Goal Details\n", f"**Goal:** {research_goal}\n"]
    for field_lines in fields:
        lines += field_lines
    return lines


def _render_provenance_line(prepared_at: float | None) -> list[str]:
    """Render the provenance and research-purposes-only caution line.

    Absent when the caller has no timestamp for this report (a demo or a
    report persisted before this field existed) -- a caution line naming
    a date this system does not actually know would misstate provenance,
    not just omit it.
    """
    if prepared_at is None:
        return []
    date = datetime.datetime.fromtimestamp(
        prepared_at, tz=datetime.timezone.utc
    ).date()
    return [
        f"_Prepared by {_SYSTEM_NAME} on {date.isoformat()}."
        " For research purposes only._",
        "",
    ]


def _render_title_and_provider(
    research_goal: str, provider: str, *, title: str = "Research Report"
) -> list[str]:
    """Render the report's H1 title and provider line. Always present.

    Split from the rest of the header (R14-1) so the table of contents can
    be inserted right after it: this is the only part of the document that
    is never conditional, so it is always what a reader sees first.

    ``title`` defaults to the pre-split document name so every existing
    caller keeps reading exactly as before; the two document renderers in
    ``report_markdown.py`` (R14-11) pass their own name -- "Research
    Overview" / "Top Ranking Hypotheses" -- so a reader who downloads or
    opens only one of the two documents can tell which from its own H1.
    """
    return [
        f"# {title} — {research_goal}",
        "",
        f"_Provider: **{provider}**_",
        "",
    ]


def _render_about_disclosure() -> list[str]:
    """Render the report-level About disclosure (R14-4).

    Research-overview-document only: nothing in the corpus attests this
    line on the ranking document, which already carries its own goal and
    provenance context. Rendered right after the title/provider line and
    before the table of contents, matching R14-1's already-established
    convention of putting the always-present opening first -- Google's own
    line ordering (goal, then About, then the table of contents) is not
    followed literally here for the same reason R14-1 does not mirror
    Google's fixed six-item nav: our Research Goal Details block is
    conditional on the run's setup, so anchoring the disclosure to the
    unconditional title keeps it from disappearing along with the goal.
    """
    return [_ABOUT_DISCLOSURE, ""]


def _render_summary_section(summary: str | None) -> list[str]:
    """Render the optional 'Summary' paragraph, or nothing when absent."""
    if not summary:
        return []
    return ["## Summary", summary, ""]
