"""Render report framing, data sources and the knowledge base.

Knowledge base topics preserve their theme hierarchy and omit citations.
"""

from __future__ import annotations

import datetime
from typing import Any

from app.run_modes import attribute_display_strings, criteria_display_strings

# Kept close to Google's published wording ("Prepared by AI co-scientist on
# 2026-06-12. For research purposes only.") but naming this system, not
# Google's -- claiming to be Google's product would misattribute the report.
_SYSTEM_NAME = "Co-Scientist"

# R14-4: byte-identical to the per-hypothesis disclaimer (R14-13,
# ``report.markdown.hypothesis._HYPOTHESIS_DISCLAIMER``, re-exported from
# here so the two never drift). Google's published research-overview.md
# carries this same "experimental system ... may be wrong" wording at the
# report level (line 5), distinct from the short provenance/caution line
# above -- one names this system and when the report ran, the other states
# what the system is and cautions that its output may be wrong. Defined
# here, the lower module in the import chain (``report.markdown.hypothesis``
# already imports ``_SYSTEM_NAME`` from this module), so the per-hypothesis
# copy can import this constant instead of duplicating the string.
_ABOUT_DISCLOSURE = (
    "**About**: *This is an experimental system for generating novel and"
    " testable hypotheses. The hypotheses are generated by a model and"
    " may be wrong. For research purposes only.*"
)


def _render_setup_list(label: str, values: list[str]) -> list[str]:
    """Render a 'Label:' bullet list, or nothing when there is no content."""
    if not values:
        return []
    return [f"**{label}:**\n"] + [f"- {value}" for value in values] + [""]


def _plain_setup_strings(items: Any) -> list[str]:
    """Coerce a Requirements/Attributes setup value into display strings."""
    return [str(item) for item in items or [] if str(item).strip()]


def _render_research_goal_details(
    research_goal: str,
    setup: dict[str, Any] | None,
) -> list[str]:
    """Render the research goal and its researcher-authored setup."""
    if not isinstance(setup, dict):
        return []
    fields = [
        _render_setup_list(
            "Requirements", _plain_setup_strings(setup.get("requirements"))
        ),
        _render_setup_list(
            "Attributes", attribute_display_strings(setup.get("attributes"))
        ),
        _render_setup_list(
            "Criteria", criteria_display_strings(setup.get("criteria"))
        ),
    ]
    if not any(fields):
        return []
    lines = ["## Research Goal Details\n", f"**Goal:** {research_goal}\n"]
    for field_lines in fields:
        lines += field_lines
    return lines


def _render_provenance_line(prepared_at: float | None) -> list[str]:
    """Render the provenance and research-purposes-only caution line.

    Absent when the caller has no timestamp for this report (a demo or a
    report persisted before this field existed) -- a caution line naming
    a date this system does not actually know would misstate provenance,
    not just omit it.
    """
    if prepared_at is None:
        return []
    date = datetime.datetime.fromtimestamp(
        prepared_at, tz=datetime.timezone.utc
    ).date()
    return [
        f"_Prepared by {_SYSTEM_NAME} on {date.isoformat()}."
        " For research purposes only._",
        "",
    ]


def _render_title_and_provider(research_goal: str, provider: str) -> list[str]:
    """Render the report's H1 title and provider line. Always present.

    Split from the rest of the header (R14-1) so the table of contents can
    be inserted right after it: this is the only part of the document that
    is never conditional, so it is always what a reader sees first.
    """
    return [
        f"# Research Report — {research_goal}",
        "",
        f"_Provider: **{provider}**_",
        "",
    ]


def _render_about_disclosure() -> list[str]:
    """Render the report-level About disclosure (R14-4)."""
    return [_ABOUT_DISCLOSURE, ""]


def _render_summary_section(summary: str | None) -> list[str]:
    """Render the optional 'Summary' paragraph, or nothing when absent."""
    if not summary:
        return []
    return ["## Summary", summary, ""]


def _section_heading(section: list[str]) -> str | None:
    """Return one section's own leading '## ' heading text, or None."""
    for line in section:
        text = line.strip()
        if not text:
            continue
        return text[3:].strip() if text.startswith("## ") else None
    return None


def _render_table_of_contents(sections: list[list[str]]) -> list[str]:
    """Render the nav list of every section this render actually produced."""
    labels = [
        heading
        for section in sections
        if (heading := _section_heading(section)) is not None
    ]
    if not labels:
        return []
    lines = ["#### Table of contents:", ""]
    lines += [f"- {label}" for label in labels]
    lines.append("")
    return lines


def _aggregate_retrieval_calls(
    calls: list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    """Group a run's searches by source: how many, and what they served."""
    aggregated: dict[str, dict[str, Any]] = {}
    seen_by_source: dict[str, set[str]] = {}
    for call in calls:
        source = str(call.get("source") or "")
        if not source:
            continue
        bucket = aggregated.setdefault(source, {"count": 0, "questions": []})
        bucket["count"] += 1
        question = str(call.get("question") or "").strip()
        # question_id is TEXT NOT NULL, which permits '' -- an empty id
        # must never read as "the same question already seen", so
        # dedup falls back to the question text itself rather than
        # collapsing every id-less row from one source into the first.
        dedup_key = str(call.get("question_id") or "") or question
        seen = seen_by_source.setdefault(source, set())
        if question and dedup_key not in seen:
            seen.add(dedup_key)
            bucket["questions"].append(question)
    return aggregated


def _render_retrieval_summary(calls: list[dict[str, Any]]) -> list[str]:
    """Render per-source search counts and the questions they served."""
    aggregated = _aggregate_retrieval_calls(calls)
    if not aggregated:
        return []
    lines = ["**Literature searches:**", ""]
    for source in sorted(aggregated):
        bucket = aggregated[source]
        count = bucket["count"]
        noun = "search" if count == 1 else "searches"
        lines.append(f"- {source}: {count} {noun}")
        lines.extend(f"  - {q}" for q in bucket["questions"])
    lines.append("")
    return lines


def _render_data_source_notice(skills_used: dict[str, int]) -> list[str]:
    """Name the third-party databases this run queried, and their terms."""
    if not skills_used:
        return []
    named = ", ".join(sorted(skills_used))
    return [
        f"This run queried the following third-party sources: {named}. "
        "Their terms of use are separate from this system's licence and "
        "are listed per source in `vendor/science-skills/"
        "SKILL_LICENSES.md`. Review them before relying on or "
        "redistributing these results.",
        "",
    ]


def _render_data_sources_section(
    skills_used: dict[str, int], retrieval_calls: list[dict[str, Any]]
) -> list[str]:
    """Render the combined 'Data sources' section, or nothing when empty."""
    body = _render_data_source_notice(skills_used)
    body += _render_retrieval_summary(retrieval_calls)
    if not body:
        return []
    return ["", "## Data sources", "", *body]


def _render_topic(topic: dict[str, Any]) -> list[str]:
    """Render one topic as a named subject heading with its prose."""
    title = str(topic.get("title") or "").strip()
    if not title:
        return []
    lines = [f"#### {title}\n"]
    for key in ("summary", "detail", "uncertainty"):
        text = str(topic.get(key) or "").strip()
        if text:
            lines.append(f"{text}\n")
    return lines


_FLAT_LABEL = "Knowledge Summary"
"""Heading for topics carrying no theme -- the flat fallback shape.

Deliberately not reused for a themed section: it is the one visible mark
distinguishing the degraded path (the research-overview call's own capped
flat topics) from a funded deep synthesis.
"""


def _render_knowledge_base_markdown(topics: list[dict[str, Any]]) -> list[str]:
    """Render the 'Knowledge Base' section, or nothing when no topics exist."""
    lines: list[str] = []
    label = ""
    for topic in topics:
        if not isinstance(topic, dict):
            continue
        rendered = _render_topic(topic)
        if not rendered:
            continue
        label, heading = _theme_heading(topic, label)
        lines += heading + rendered
    if not lines:
        return []
    return ["\n## Knowledge Base\n", *lines]


def _theme_heading(
    topic: dict[str, Any], current: str
) -> tuple[str, list[str]]:
    """Return the heading label in force and the line it needs, if any."""
    label = str(topic.get("theme") or "").strip() or _FLAT_LABEL
    if label == current:
        return label, []
    return label, [f"### {label}\n"]
