// Rounded weight-400 glyphs match Google Symbols ROND 100.
// Inline paths avoid font FOUT and remain safe during prerendering.

import {readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(HERE, '../node_modules/@material-symbols/svg-400/rounded');
const DEST = resolve(HERE, '../src/components/icon.tsx');

// Public icon name -> Material Symbols glyph file stem. Same name unless the
// current Material Symbols set renamed the glyph.
const ICONS = {
  // Org-chart glyph -- the landing page's Supervisor agent card.
  account_tree: 'account_tree',
  add: 'add',
  arrow_back: 'arrow_back',
  arrow_downward: 'arrow_downward',
  article: 'article',
  assignment: 'assignment',
  check: 'check',
  // Chessboard glyph — the reference's "Playing tournament" progress step.
  chess: 'chess',
  close: 'close',
  computer: 'computer',
  content_copy: 'content_copy',
  dark_mode: 'dark_mode',
  database: 'database',
  download: 'download',
  edit: 'edit',
  edit_square: 'edit_square',
  emoji_events: 'trophy',
  // Google's internal keyhole shield is unavailable publicly; encrypted supplies that shape.
  // Plain shield is empty and security is quartered.
  encrypted: 'encrypted',
  expand_less: 'keyboard_arrow_up',
  expand_more: 'keyboard_arrow_down',
  format_list_numbered: 'format_list_numbered',
  // Overlapping bubbles denote a transcript, unlike the single-message chat glyph.
  forum: 'forum',
  // Double helix -- the landing page's Evolution agent card.
  genetics: 'genetics',
  // The recents clock-rewind glyph (clock face + counterclockwise arrow), not
  // the plain 'schedule' clock.
  history: 'history',
  // Overlapping circles -- the landing page's Proximity agent card.
  join: 'join',
  // Podium bars -- the landing page's Ranking agent card.
  leaderboard: 'leaderboard',
  light_mode: 'light_mode',
  // The product uses a plain bulb; emoji_objects adds a filament and rays.
  lightbulb: 'lightbulb',
  // Results needs a whole-report glyph; summarize already denotes Research Overview.
  lab_profile: 'lab_profile',
  menu: 'menu',
  menu_book: 'menu_book',
  // Outlined brain — the settings menu's "Model" row. Reads as model/AI and
  // matches the airy outlined set.
  neurology: 'neurology',
  open_in_new: 'open_in_new',
  // Appearance uses the painter's palette glyph.
  palette: 'palette',
  // The landing page's human-review safety card.
  person: 'person',
  // Shield with a magnifier -- the landing page's goal-screening card.
  policy: 'policy',
  // "Generating ideas" progress step — a speech bubble with a pencil.
  rate_review: 'rate_review',
  refresh: 'refresh',
  // "Reviewing ideas" progress step — a starred review badge.
  reviews: 'reviews',
  search: 'search',
  send: 'send-fill',
  settings: 'settings',
  stars: 'stars',
  // Filled square — the composer's Stop control while a turn is in flight,
  // matching the send glyph's filled treatment.
  stop: 'stop-fill',
  summarize: 'summarize',
  // Shield with a check -- the landing page's idea-screening card.
  verified_user: 'verified_user',
  warning: 'warning',
};

function extractPaths(svg) {
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1]);
  if (!ds.length) throw new Error('no path found');
  return ds;
}

const names = Object.keys(ICONS).sort();
const entries = names.map(name => {
  const svg = readFileSync(`${SRC}/${ICONS[name]}.svg`, 'utf8');
  const paths = extractPaths(svg);
  const body = paths.map(d => `<path d="${d}" />`).join('');
  return {name, body: paths.length > 1 ? `<>${body}</>` : body};
});

const map = entries.map(e => `  ${e.name}: ${e.body},`).join('\n');

const out = `import type {SVGProps} from 'react';

// GENERATED by scripts/generate_icons.mjs from @material-symbols/svg-400.
// Do not edit by hand; add icons in the generator and re-run it.
//
// Authentic Material Symbols Rounded glyphs (weight 400) — the public cut of
// Google Symbols ROND 100, which the live Gemini Enterprise product uses —
// rendered as inline SVG so the set is tree-shakeable, prerender-safe, and
// free of font FOUT. Glyphs use the Material Symbols 0 -960 960 960 grid and
// are filled paths (never stroked).

export type IconName = keyof typeof ICON_PATHS;

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children' | 'name'> & {
  name: IconName;
};

const ICON_PATHS = {
${map}
};

export function Icon({name, className, ...props}: IconProps) {
  return (
    <svg
      aria-hidden={props['aria-hidden'] ?? true}
      className={className}
      fill="currentColor"
      focusable="false"
      height="1em"
      viewBox="0 -960 960 960"
      width="1em"
      {...props}
    >
      {ICON_PATHS[name]}
    </svg>
  );
}
`;

writeFileSync(DEST, out);
console.log(`Wrote ${names.length} authentic Material Symbols to ${DEST}`);
