// Generates src/components/icon.tsx from authentic Material Symbols Rounded
// glyphs (weight 400) shipped by @material-symbols/svg-400. Rounded matches
// the Google Symbols ROND-100 axis the live Gemini Enterprise product renders
// its icons with (measured July 2026).
//
// The glyph outlines are inlined as SVG paths so the icon set stays
// tree-shakeable, prerender-safe, and free of font FOUT while remaining
// pixel-identical to Google's Material Symbols.
//
// To add an icon: add a `publicName: 'material-symbols-file-stem'` entry to
// ICONS below, then run `node scripts/generate_icons.mjs`.

import {readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(
  HERE,
  '../node_modules/@material-symbols/svg-400/rounded',
);
const DEST = resolve(HERE, '../src/components/icon.tsx');

// Public icon name -> Material Symbols glyph file stem. Same name unless the
// current Material Symbols set renamed the glyph.
const ICONS = {
  add: 'add',
  arrow_back: 'arrow_back',
  arrow_forward: 'arrow_forward',
  article: 'article',
  check_circle: 'check_circle',
  close: 'close',
  computer: 'computer',
  content_copy: 'content_copy',
  dark_mode: 'dark_mode',
  database: 'database',
  download: 'download',
  edit: 'edit',
  edit_square: 'edit_square',
  emoji_events: 'trophy',
  // Shield-with-a-keyhole. The reference product renders the Google-internal
  // 'android_security_privacy_safe' ligature (not in the public set); of the
  // public Material Symbols, 'encrypted' is the true shield-with-keyhole
  // (plain 'shield' is an empty shield, 'security' is quartered).
  encrypted: 'encrypted',
  expand_less: 'keyboard_arrow_up',
  expand_more: 'keyboard_arrow_down',
  format_list_numbered: 'format_list_numbered',
  // The recents clock-rewind glyph (clock face + counterclockwise arrow), not
  // the plain 'schedule' clock.
  history: 'history',
  light_mode: 'light_mode',
  // The plain outline light bulb (bulb body + base bars, no rays) the Idea
  // Generation product renders in its agent glyph — not 'emoji_objects', which
  // adds a filament and radiating rays.
  lightbulb: 'lightbulb',
  menu: 'menu',
  menu_book: 'menu_book',
  open_in_new: 'open_in_new',
  // Research-overview glyph (a page of content lines under an analytical lens).
  // The reference product's own overview glyph is not in the saved capture, so
  // this is the closest Material Symbols match.
  overview: 'overview',
  refresh: 'refresh',
  search: 'search',
  send: 'send-fill',
  settings: 'settings',
  stars: 'stars',
  warning: 'warning',
};

function extractPaths(svg) {
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1]);
  if (!ds.length) throw new Error('no path found');
  return ds;
}

const names = Object.keys(ICONS).sort();
const entries = names.map(name => {
  const svg = readFileSync(`${SRC}/${ICONS[name]}.svg`, 'utf8');
  const body = extractPaths(svg)
    .map(d => `<path d="${d}" />`)
    .join('');
  return {name, body};
});

const union = names.map(n => `  | '${n}'`).join('\n');
const map = entries.map(e => `  ${e.name}: <>${e.body}</>,`).join('\n');

const out = `import type {ReactNode, SVGProps} from 'react';

// GENERATED by scripts/generate_icons.mjs from @material-symbols/svg-400.
// Do not edit by hand; add icons in the generator and re-run it.
//
// Authentic Material Symbols Rounded glyphs (weight 400) — the public cut of
// Google Symbols ROND 100, which the live Gemini Enterprise product uses —
// rendered as inline SVG so the set is tree-shakeable, prerender-safe, and
// free of font FOUT. Glyphs use the Material Symbols 0 -960 960 960 grid and
// are filled paths (never stroked).

export type IconName =
${union};

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children' | 'name'> & {
  name: IconName;
};

const ICON_PATHS: Record<IconName, ReactNode> = {
${map}
};

export function Icon({name, className, ...props}: IconProps) {
  return (
    <svg
      aria-hidden={props['aria-hidden'] ?? true}
      className={className}
      fill="currentColor"
      focusable="false"
      height="1em"
      viewBox="0 -960 960 960"
      width="1em"
      {...props}
    >
      {ICON_PATHS[name]}
    </svg>
  );
}
`;

writeFileSync(DEST, out);
console.log(`Wrote ${names.length} authentic Material Symbols to ${DEST}`);
