"""Stopword vocabulary for the deterministic offline backend's term mining.

Split out of ``co_scientist.offline_content`` to keep that module under the
repo's file-length ceiling. Holds only the noise-word set ``subject_terms``
filters out of a prompt's research-goal text; the extraction logic and the
sentence templates that consume it stay in ``offline_content``. Re-exported
from there so existing importers are unaffected.
"""

# Words that carry no subject meaning but survive a naive keyword pass over a
# research goal ("What mechanisms drive antibiotic resistance in ..."), plus
# the agent/prompt scaffolding vocabulary. Every prompt opens with its
# agent's name, and a prompt that never labels the goal (evolution.md, say)
# is scanned from the top -- without these, evolved ideas came out reading
# "Agent constrains evolution ...".
_STOPWORDS = frozenset(
    {
        "about",
        "above",
        "after",
        "against",
        "all",
        "also",
        "and",
        "are",
        "based",
        "because",
        "been",
        "before",
        "being",
        "below",
        "between",
        "both",
        "but",
        "can",
        "could",
        "designed",
        "does",
        "drive",
        "driven",
        "during",
        "each",
        "either",
        "from",
        "further",
        "generate",
        "goal",
        "task",
        "meta-review",
        "reviews",
        "review",
        "proximity",
        "supervisor",
        "reflection",
        "ranking",
        "generation",
        "evolution",
        "agents",
        "agent",
        "had",
        "has",
        "have",
        "having",
        "hypotheses",
        "hypothesis",
        "help",
        "here",
        "how",
        "however",
        "identify",
        "into",
        "its",
        "itself",
        "might",
        "more",
        "most",
        "much",
        "must",
        "new",
        "novel",
        "only",
        "other",
        "over",
        "own",
        "particular",
        "potential",
        "propose",
        "research",
        "same",
        "should",
        "since",
        "some",
        "such",
        "suggest",
        "than",
        "that",
        "the",
        "their",
        "them",
        "then",
        "there",
        "these",
        "they",
        "this",
        "those",
        "through",
        "under",
        "until",
        "use",
        "used",
        "using",
        "very",
        "was",
        "were",
        "what",
        "when",
        "where",
        "which",
        "while",
        "who",
        "why",
        "will",
        "with",
        "within",
        "would",
        "you",
        "your",
    }
)
