import {type ReactNode} from 'react';

export const REPORT_DOCUMENT_CLASSES =
  'cosci-report-document mx-auto mt-9 mb-24 w-[min(100%_-_3rem,58rem)] text-base leading-[1.7] max-[720px]:mt-5 max-[720px]:mb-12 max-[720px]:w-[min(100%_-_1.2rem,100%)] max-[720px]:max-w-none';

export const REPORT_GENERATED_CHIP_CLASSES =
  'cosci-generated-chip inline-flex items-center gap-[0.45rem] rounded-lg bg-[var(--cosci-panel)] px-[0.65rem] py-[0.45rem] text-[0.82rem] leading-[1.2] text-[var(--cosci-muted)]';

export const REPORT_H2_CLASSES =
  'mt-9 mb-5 text-[clamp(2.15rem,3.2vw,2.75rem)] leading-[1.12] font-normal tracking-normal max-[720px]:text-[clamp(1.65rem,8vw,2.15rem)]';

export const REPORT_H3_CLASSES = 'mt-[1.4rem] mb-3 text-[1.35rem] font-medium';

export const REPORT_H4_CLASSES = 'mt-4 mb-[0.35rem] text-base font-medium';

export const REPORT_LIST_CLASSES = 'mt-[0.45rem] mb-0 pl-[1.35rem]';

export const REPORT_SECTION_CLASSES = 'cosci-overview-section mt-8';

export const REPORT_SECTION_LIST_ITEM_CLASSES =
  'my-[0.6rem] grid gap-[0.15rem]';

export const REPORT_SECTION_LIST_META_CLASSES =
  'text-[0.88rem] text-[var(--cosci-muted)]';

export function ReportDocument({
  title,
  children,
  className,
}: {
  title: string;
  children: ReactNode;
  className?: string;
}) {
  const documentClassName = [REPORT_DOCUMENT_CLASSES, className]
    .filter(Boolean)
    .join(' ');
  return (
    <article className={documentClassName}>
      <div className={REPORT_GENERATED_CHIP_CLASSES}>
        <span aria-hidden="true">-</span>
        Generated by Co-Scientist - Version: March 16 2026
      </div>
      <h2 className={REPORT_H2_CLASSES}>{title}</h2>
      {children}
    </article>
  );
}

export function ReportList({title, values}: {title: string; values: string[]}) {
  if (!values.length) return null;
  return (
    <section className="cosci-report-list">
      <h4 className={REPORT_H4_CLASSES}>{title}:</h4>
      <ul className={REPORT_LIST_CLASSES}>
        {values.map(value => (
          <li key={value}>{value}</li>
        ))}
      </ul>
    </section>
  );
}
