"""Builds tiny, real PDF files from raw PDF syntax for heading tests.

Deliberately hand-rolled rather than generated by a writer library: the
point of these fixtures is to drive the real ``pypdf`` parser end to end
(see the module docstring trap noted in ``test_document_upload.py``), and
a from-scratch content stream gives exact control over font size/weight
per line without needing any drawing dependency. An outline, when one is
wanted, is added afterward through ``pypdf.PdfWriter`` itself -- still
real pypdf, just the part of its own API built for that job.
"""

from __future__ import annotations

import io

from pypdf import PdfReader, PdfWriter

# One line per (text, font resource name, size, x, y). Font resource names
# are looked up in each page's own /Font dict (see _page_object below).
Line = tuple[str, str, float, float, float]


def _escape(text: str) -> str:
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def _content_stream(lines: list[Line]) -> bytes:
    ops = [
        f"BT /{font} {size} Tf {x} {y} Td ({_escape(text)}) Tj ET"
        for text, font, size, x, y in lines
    ]
    return "\n".join(ops).encode("latin-1")


def _page_object(content_num: int, font_nums: dict[str, int]) -> bytes:
    fonts = " ".join(f"/{name} {num} 0 R" for name, num in font_nums.items())
    return (
        f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 400 500] "
        f"/Resources << /Font << {fonts} >> >> "
        f"/Contents {content_num} 0 R >>"
    ).encode("latin-1")


def _build_objects(
    pages_lines: list[list[Line]],
) -> tuple[dict[int, bytes], list[int]]:
    font_nums = {"F1": 100, "F2": 101}
    objects: dict[int, bytes] = {
        100: b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        101: b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    }
    page_nums: list[int] = []
    next_num = 10
    for lines in pages_lines:
        page_num, content_num = next_num, next_num + 1
        next_num += 2
        page_nums.append(page_num)
        stream = _content_stream(lines)
        objects[content_num] = (
            f"<< /Length {len(stream)} >>\nstream\n".encode("latin-1")
            + stream
            + b"\nendstream"
        )
        objects[page_num] = _page_object(content_num, font_nums)
    kids = " ".join(f"{n} 0 R" for n in page_nums)
    objects[2] = (
        f"<< /Type /Pages /Kids [{kids}] /Count {len(page_nums)} >>"
    ).encode("latin-1")
    objects[1] = b"<< /Type /Catalog /Pages 2 0 R >>"
    return objects, page_nums


def _serialize(objects: dict[int, bytes]) -> bytes:
    """Assemble objects into a minimal well-formed PDF.

    Offsets are computed from actual byte positions rather than hand-
    counted, since hand-counted xref offsets are the fiddliest part of
    writing raw PDF and the easiest to get silently wrong.
    """
    all_nums = sorted(objects)
    max_num = max(all_nums)
    buf = io.BytesIO()
    buf.write(b"%PDF-1.4\n")
    offsets: dict[int, int] = {}
    for num in all_nums:
        offsets[num] = buf.tell()
        buf.write(f"{num} 0 obj\n".encode("latin-1"))
        buf.write(objects[num])
        buf.write(b"\nendobj\n")
    xref_offset = buf.tell()
    buf.write(f"xref\n0 {max_num + 1}\n".encode("latin-1"))
    buf.write(b"0000000000 65535 f \n")
    for num in range(1, max_num + 1):
        buf.write(f"{offsets.get(num, 0):010d} 00000 n \n".encode("latin-1"))
    buf.write(
        (
            f"trailer\n<< /Size {max_num + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref_offset}\n%%EOF"
        ).encode("latin-1")
    )
    return buf.getvalue()


def build_pdf(
    pages_lines: list[list[Line]],
    outline: list[tuple[str, int]] | None = None,
) -> bytes:
    """Build a real PDF from per-page text-object lines.

    ``outline``, when given, is a flat list of (title, target page index).
    """
    objects, _ = _build_objects(pages_lines)
    raw = _serialize(objects)
    if not outline:
        return raw

    reader = PdfReader(io.BytesIO(raw))
    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    for title, page_index in outline:
        writer.add_outline_item(title, page_index)
    out = io.BytesIO()
    writer.write(out)
    return out.getvalue()
