"""Report headers retain the research disclosure and timestamp provenance."""

import datetime
from collections.abc import Callable

from app.report import markdown as report_markdown
from app.report.markdown.hypothesis import _HYPOTHESIS_DISCLAIMER

_DocumentFn = Callable[[report_markdown.ReportMarkdownInputs], str]


def _markdown(fn: _DocumentFn) -> str:
    """Render a minimal report through the given document function."""
    return fn(
        report_markdown.ReportMarkdownInputs(
            research_goal="Explain the cardiac benefit.",
            provider="engine",
            top_hypotheses=[],
        )
    )


def test_the_overview_document_carries_the_about_disclosure() -> None:
    """The disclosure renders, verbatim, on the Goal Report document."""
    markdown = _markdown(report_markdown.render_report_markdown)

    assert (
        "**About**: *This is an experimental system for generating novel"
        " and testable hypotheses. The hypotheses are generated by a"
        " model and may be wrong. For research purposes only.*"
    ) in markdown


def test_it_is_byte_identical_to_the_per_hypothesis_disclaimer() -> None:
    """One real wording, not two near-identical strings drifting apart."""
    markdown = _markdown(report_markdown.render_report_markdown)

    assert _HYPOTHESIS_DISCLAIMER in markdown


def test_it_renders_before_the_table_of_contents() -> None:
    """Matches the published order: About, then the nav list."""
    markdown = report_markdown.render_report_markdown(
        report_markdown.ReportMarkdownInputs(
            research_goal="Explain the cardiac benefit.",
            provider="engine",
            top_hypotheses=[],
            # A populated section so the table of contents actually
            # renders (it is itself omitted on an empty report).
            meta_review={"summary": "Ideas converge on a shared mechanism."},
        )
    )

    about_at = markdown.index("**About**:")
    toc_at = markdown.index("#### Table of contents:")
    assert about_at < toc_at


def _provenance_markdown(prepared_at: float | None) -> str:
    """Render a minimal report carrying only the given prepared_at."""
    return report_markdown.render_report_markdown(
        report_markdown.ReportMarkdownInputs(
            research_goal="Explain the cardiac benefit.",
            provider="engine",
            top_hypotheses=[],
            prepared_at=prepared_at,
        )
    )


def test_the_header_carries_the_research_purposes_only_caution() -> None:
    """The caution line renders verbatim."""
    markdown = _provenance_markdown(1_700_000_000.0)

    assert "For research purposes only." in markdown


def test_the_header_names_this_system_not_googles() -> None:
    """Provenance is attributed to this system, never "AI co-scientist"."""
    markdown = _provenance_markdown(1_700_000_000.0)

    assert "Prepared by Co-Scientist on" in markdown
    assert "AI co-scientist" not in markdown


def test_the_date_is_derived_from_prepared_at_not_wall_clock() -> None:
    """The rendered date matches the supplied timestamp, not datetime.now()."""
    timestamp = 1_700_000_000.0
    expected = (
        datetime.datetime.fromtimestamp(timestamp, tz=datetime.timezone.utc)
        .date()
        .isoformat()
    )

    markdown = _provenance_markdown(timestamp)

    assert expected in markdown


def test_no_prepared_at_renders_no_provenance_line() -> None:
    """A report with no known preparation time carries no caution line.

    Covers a report persisted before this field existed rather than
    stating a date this system does not actually know. Checks the
    provenance line's own wording, not the bare "For research purposes
    only" phrase -- the R14-4 About disclosure (report/markdown/header.py)
    carries that same closing phrase unconditionally, on every render.
    """
    markdown = _provenance_markdown(None)

    assert "Prepared by" not in markdown
