"""R14-4: the Goal Report document carries a report-level disclosure.

Google's published ``research-overview.md`` carries, right after the goal
and before its table of contents (line 5): "**About**: This is an
experimental system for generating novel and testable hypotheses. The
hypotheses are generated by a model and may be wrong. For research purposes
only." (``docs/CORPUS-EXTRACTION.md`` R14-4) -- distinct from the short
"Prepared by ... date" provenance line (R12-20) already built. This pins
that the disclosure renders, byte-identical to the per-hypothesis instance
of the same wording (R14-13), unconditionally on every report.
"""

from collections.abc import Callable

from app.report import markdown as report_markdown
from app.report.markdown.hypothesis import _HYPOTHESIS_DISCLAIMER

_DocumentFn = Callable[[report_markdown.ReportMarkdownInputs], str]


def _markdown(fn: _DocumentFn) -> str:
    """Render a minimal report through the given document function."""
    return fn(
        report_markdown.ReportMarkdownInputs(
            research_goal="Explain the cardiac benefit.",
            provider="engine",
            top_hypotheses=[],
        )
    )


def test_the_overview_document_carries_the_about_disclosure() -> None:
    """The disclosure renders, verbatim, on the Goal Report document."""
    markdown = _markdown(report_markdown.render_report_markdown)

    assert (
        "**About**: *This is an experimental system for generating novel"
        " and testable hypotheses. The hypotheses are generated by a"
        " model and may be wrong. For research purposes only.*"
    ) in markdown


def test_it_is_byte_identical_to_the_per_hypothesis_disclaimer() -> None:
    """One real wording, not two near-identical strings drifting apart."""
    markdown = _markdown(report_markdown.render_report_markdown)

    assert _HYPOTHESIS_DISCLAIMER in markdown


def test_it_renders_before_the_table_of_contents() -> None:
    """Matches the published order: About, then the nav list."""
    markdown = report_markdown.render_report_markdown(
        report_markdown.ReportMarkdownInputs(
            research_goal="Explain the cardiac benefit.",
            provider="engine",
            top_hypotheses=[],
            # A populated section so the table of contents actually
            # renders (it is itself omitted on an empty report).
            meta_review={"summary": "Ideas converge on a shared mechanism."},
        )
    )

    about_at = markdown.index("**About**:")
    toc_at = markdown.index("#### Table of contents:")
    assert about_at < toc_at
