from __future__ import annotations

import datetime
from typing import Any

from co_scientist.core.run_modes import attribute_display_strings, criteria_display_strings

# Attribute reports to this system rather than misattribute them to Google.
_SYSTEM_NAME = "Open Co-Scientist"

# Share the experimental caution with hypothesis entries so the disclosures
# cannot drift.
_ABOUT_DISCLOSURE = (
    "**About**: *This is an experimental system for generating novel and"
    " testable hypotheses. The hypotheses are generated by a model and"
    " may be wrong. For research purposes only.*"
)


def _render_setup_list(label: str, values: list[str]) -> list[str]:
    if not values:
        return []
    return [f"**{label}:**\n"] + [f"- {value}" for value in values] + [""]


def _plain_setup_strings(items: Any) -> list[str]:
    return [str(item) for item in items or [] if str(item).strip()]


def _render_research_goal_details(
    research_goal: str,
    setup: dict[str, Any] | None,
) -> list[str]:
    if not isinstance(setup, dict):
        return []
    fields = [
        _render_setup_list("Requirements", _plain_setup_strings(setup.get("requirements"))),
        _render_setup_list("Attributes", attribute_display_strings(setup.get("attributes"))),
        _render_setup_list("Criteria", criteria_display_strings(setup.get("criteria"))),
    ]
    if not any(fields):
        return []
    lines = ["## Research Goal Details\n", f"**Goal:** {research_goal}\n"]
    for field_lines in fields:
        lines += field_lines
    return lines


def _render_provenance_line(prepared_at: float | None) -> list[str]:
    """Omit unknown timestamps rather than invent report provenance."""
    if prepared_at is None:
        return []
    date = datetime.datetime.fromtimestamp(prepared_at, tz=datetime.timezone.utc).date()
    return [
        f"_Prepared by {_SYSTEM_NAME} on {date.isoformat()}. For research purposes only._",
        "",
    ]


def _render_title_and_provider(research_goal: str, provider: str) -> list[str]:
    return [
        f"# Research Report — {research_goal}",
        "",
        f"_Provider: **{provider}**_",
        "",
    ]


def _render_about_disclosure() -> list[str]:
    return [_ABOUT_DISCLOSURE, ""]


def _render_summary_section(summary: str | None) -> list[str]:
    if not summary:
        return []
    return ["## Summary", summary, ""]


def _section_heading(section: list[str]) -> str | None:
    for line in section:
        text = line.strip()
        if not text:
            continue
        return text[3:].strip() if text.startswith("## ") else None
    return None


def _render_table_of_contents(sections: list[list[str]]) -> list[str]:
    labels = [heading for section in sections if (heading := _section_heading(section)) is not None]
    if not labels:
        return []
    lines = ["#### Table of contents:", ""]
    lines += [f"- {label}" for label in labels]
    lines.append("")
    return lines


def _aggregate_retrieval_calls(
    calls: list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    aggregated: dict[str, dict[str, Any]] = {}
    seen_by_source: dict[str, set[str]] = {}
    for call in calls:
        source = str(call.get("source") or "")
        if not source:
            continue
        bucket = aggregated.setdefault(source, {"count": 0, "questions": []})
        bucket["count"] += 1
        question = str(call.get("question") or "").strip()
        # Empty question ids are valid SQL text; deduplicate by question text
        # rather than merge every id-less row.
        dedup_key = str(call.get("question_id") or "") or question
        seen = seen_by_source.setdefault(source, set())
        if question and dedup_key not in seen:
            seen.add(dedup_key)
            bucket["questions"].append(question)
    return aggregated


def _render_retrieval_summary(calls: list[dict[str, Any]]) -> list[str]:
    aggregated = _aggregate_retrieval_calls(calls)
    if not aggregated:
        return []
    lines = ["**Literature searches:**", ""]
    for source in sorted(aggregated):
        bucket = aggregated[source]
        count = bucket["count"]
        noun = "search" if count == 1 else "searches"
        lines.append(f"- {source}: {count} {noun}")
        lines.extend(f"  - {q}" for q in bucket["questions"])
    lines.append("")
    return lines


def _render_data_source_notice(skills_used: dict[str, int]) -> list[str]:
    """Third-party databases can require notice of their terms for sources this
    run actually queried.
    """
    if not skills_used:
        return []
    named = ", ".join(sorted(skills_used))
    return [
        f"This run queried the following third-party sources: {named}. "
        "Their terms of use are separate from this system's licence and "
        "are listed per source in `vendor/science-skills/"
        "SKILL_LICENSES.md`. Review them before relying on or "
        "redistributing these results.",
        "",
    ]


def _render_data_sources_section(
    skills_used: dict[str, int], retrieval_calls: list[dict[str, Any]]
) -> list[str]:
    body = _render_data_source_notice(skills_used)
    body += _render_retrieval_summary(retrieval_calls)
    if not body:
        return []
    return ["", "## Data sources", "", *body]


def _render_topic(topic: dict[str, Any]) -> list[str]:
    title = str(topic.get("title") or "").strip()
    if not title:
        return []
    lines = [f"#### {title}\n"]
    for key in ("summary", "detail", "uncertainty"):
        text = str(topic.get(key) or "").strip()
        if text:
            lines.append(f"{text}\n")
    return lines


_FLAT_LABEL = "Knowledge Summary"
"""Heading for topics carrying no theme -- the flat fallback shape.

Deliberately not reused for a themed section: it is the one visible mark
distinguishing the degraded path (the research-overview call's own capped
flat topics) from a funded deep synthesis.
"""


def _render_knowledge_base_markdown(topics: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    label = ""
    for topic in topics:
        if not isinstance(topic, dict):
            continue
        rendered = _render_topic(topic)
        if not rendered:
            continue
        label, heading = _theme_heading(topic, label)
        lines += heading + rendered
    if not lines:
        return []
    return ["\n## Knowledge Base\n", *lines]


def _theme_heading(topic: dict[str, Any], current: str) -> tuple[str, list[str]]:
    label = str(topic.get("theme") or "").strip() or _FLAT_LABEL
    if label == current:
        return label, []
    return label, [f"### {label}\n"]
