"""Persistent per-user identity for the ``cosci`` CLI.

The API now refuses to create a run (or any other caller-owned record)
for a compatibility caller sending no ``X-Client-ID`` header at all (see
``app.auth.require_client_scope``): an identity-less caller would own
nothing, its own runs invisible to it the moment it asked for them back.
``cosci`` therefore needs a default identity of its own, the same way the
workbench UI persists one in the browser's localStorage
(``frontend/src/lib/client_id.ts``) -- generated once per machine and
reused on every later invocation, so run listings stay stable across
separate ``cosci`` processes with no configuration required.
"""

from __future__ import annotations

import os
import uuid
from pathlib import Path

_FILE_NAME = "client_id"


def _config_dir() -> Path:
    """Return the directory the persistent client id is stored under.

    ``COSCIENTIST_CLI_CONFIG_DIR`` overrides the location outright --
    used by the test suite to keep the generated id off a real machine's
    home directory. Otherwise this follows the XDG convention
    (``XDG_CONFIG_HOME``, defaulting to ``~/.config``).
    """
    override = os.environ.get("COSCIENTIST_CLI_CONFIG_DIR")
    if override:
        return Path(override)
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "co-scientist"


def default_client_id() -> str:
    """Return this machine's persistent client id, creating one on first use.

    Reading and writing are not atomic against a concurrent first
    invocation racing to create the file, but the race is harmless:
    whichever id lands on disk last is what every later invocation reads,
    and losing an id generated by a process that exits immediately after
    costs nothing a user would notice. A directory that cannot be created
    or written (a read-only home, a sandboxed environment) degrades to a
    fresh id for this process alone rather than failing the command.

    Returns:
        The persisted id, generated and written to disk if none exists.
    """
    path = _config_dir() / _FILE_NAME
    try:
        existing = path.read_text().strip()
        if existing:
            return existing
    except OSError:
        pass
    generated = f"cli-{uuid.uuid4().hex}"
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(generated)
    except OSError:
        pass
    return generated
